# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import sqlite3
import Adminpage
import Registration
import reception
import patientlogin

# import stylesheet
import cs



class LoginForm(object):

    def loginUser(self):
        Name=self.UserNameLE.text()
        Password=self.PassLE.text()
        User= self.UserCB.currentText()

        # creating database
        db=sqlite3.connect("Hospital.db")

        # to load and connect database
        if User== 'Admin':
            db.execute("CREATE TABLE if not exists admin (email text, password text)")
            db.execute("INSERT INTO admin VALUES('admin@gmail.com','admin')")
            db.commit()
            CheckAdmin=db.execute("select email, password from admin where email=? and password=?",(Name,Password))
            # to check if login as admin is succesful
            if CheckAdmin.fetchall():
                message2= QMessageBox()
                message2.setWindowTitle("Login Succesful")
                message2.setInformativeText("Welcome to New Horizon Hospital" + Name)
                message2.exec_()

                # linking admin page to login
                self.window = QtWidgets.QMainWindow()
                self.OpenAdmin= Adminpage.AdminView()
                self.OpenAdmin.setupUi(self.window)
                self.window.show()

            else:
                message = QMessageBox()
                message.setWindowTitle("Login not Succesfull")
                message.setInformativeText("Please Enter Correct email and password")
                message.exec_()

        elif User == "Receptionist":
            checkReceptionist = db.execute("select email, password from Receptionist where email =? and password = ?",(Name, Password))
            if checkReceptionist.fetchall():
                message= QMessageBox()
                message.setWindowTitle("Successfull")
                message.setInformativeText("Welcome to New Horizon Hospital!, Receptionist " + Name)
                message.exec_()


                # linking receptionist page to login

                self.window = QtWidgets.QMainWindow()
                self.classreception = reception.Reception()
                self.classreception.setupUi(self.window)
                self.window.show()

            else:
                message = QMessageBox()
                message.setWindowTitle("Unsuccessfull")
                message.setInformativeText("Please Enter correct email address /password! ")
                message.exec_()


        elif User == "Patient":
            # creating a new table for patients
            ID = "0"  # Just to save the emails
            #db.execute("drop table SaveEmails")
            db.execute("create table if not exists SaveEmails (ID, Email text)")
            db.execute("insert into SaveEmails values(?,?)", (ID, Name))
            db.commit()
            check = db.execute("select email, password from PatientEmail where email =? and password = ?",
                               (Name, Password))
            # If the email and password and usertype belongs to a patient, log In otherwise it gives a message
            if check.fetchall():
                message = QMessageBox()
                message.setWindowTitle("Successfull")
                message.setInformativeText("Welcome to New Horizon Hospital! " + Name)
                message.exec_()

                # to open patient page
                self.window = QtWidgets.QMainWindow()
                self.classPatientlog = patientlogin.Patientlog()
                self.classPatientlog.setupUi(self.window)
                self.window.show()


            else:
                message = QMessageBox()
                message.setWindowTitle("Unsuccessfull")
                message.setInformativeText("Please Enter correct email address /password! ")
                message.exec_()

        db.close()
        self.UserNameLE.clear()
        self.PassLE.clear()

    # defining singup button
    def SignUPBtn(self):
        self.window = QtWidgets.QMainWindow()
        self.OpenSignUp = Registration.RegisterationForm()
        self.OpenSignUp.setupUi(self.window)
        self.window.show()




    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SigninPB = QtWidgets.QPushButton(self.centralwidget)
        self.SigninPB.setGeometry(QtCore.QRect(370, 330, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Light")
        font.setPointSize(10)
        self.SigninPB.setFont(font)
        self.SigninPB.setStyleSheet("background-color: rgb(138, 173, 255);")
        self.SigninPB.setObjectName("SigninPB")
        self.SigninPB.clicked.connect(self.loginUser)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(310, 260, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Light")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 180, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Light")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 120, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Light")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(360, 40, 131, 51))
        self.label_8.setStyleSheet("image: url(:/background/images.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 90, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Light")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.UserNameLE = QtWidgets.QLineEdit(self.centralwidget)
        self.UserNameLE.setGeometry(QtCore.QRect(310, 160, 241, 31))
        self.UserNameLE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.UserNameLE.setObjectName("UserNameLE")
        self.PassLE = QtWidgets.QLineEdit(self.centralwidget)
        self.PassLE.setGeometry(QtCore.QRect(310, 220, 241, 31))
        self.PassLE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PassLE.setObjectName("PassLE")
        # to hide password
        self.PassLE.setEchoMode(QtWidgets.QLineEdit.Password)

        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(0, -30, 871, 621))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(13)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/background/H.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.UserCB = QtWidgets.QComboBox(self.centralwidget)
        self.UserCB.setGeometry(QtCore.QRect(390, 270, 131, 31))
        self.UserCB.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.UserCB.setObjectName("UserCB")
        self.UserCB.addItem("")
        self.UserCB.setItemText(0, "")
        self.UserCB.addItem("")
        self.UserCB.addItem("")
        self.UserCB.addItem("")
        self.SigupPB = QtWidgets.QPushButton(self.centralwidget)
        self.SigupPB.setGeometry(QtCore.QRect(420, 390, 121, 41))
        self.SigupPB.clicked.connect(self.SignUPBtn)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Light")
        font.setPointSize(10)
        self.SigupPB.setFont(font)
        self.SigupPB.setStyleSheet("background-color: rgb(138, 173, 255);")
        self.SigupPB.setObjectName("SigupPB")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(260, 380, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Light")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_9.raise_()
        self.SigninPB.raise_()
        self.label_5.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.label_8.raise_()
        self.label.raise_()
        self.UserNameLE.raise_()
        self.PassLE.raise_()
        self.UserCB.raise_()
        self.SigupPB.raise_()
        self.label_6.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SigninPB.setText(_translate("MainWindow", "Sign in"))
        self.label_5.setText(_translate("MainWindow", "User Type"))
        self.label_3.setText(_translate("MainWindow", "Password"))
        self.label_2.setText(_translate("MainWindow", "Username"))
        self.label.setText(_translate("MainWindow", "Login"))
        self.UserCB.setItemText(1, _translate("MainWindow", "Admin"))
        self.UserCB.setItemText(2, _translate("MainWindow", "Receptionist"))
        self.UserCB.setItemText(3, _translate("MainWindow", "Patient"))
        self.SigupPB.setText(_translate("MainWindow", "Sign UP"))
        self.label_6.setText(_translate("MainWindow", "Create an Account"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = LoginForm()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
