# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reception.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QCoreApplication
import sqlite3

import cs


class Reception(object):
    # Function for approval of appointments
    def ApproveApp(self):
        # Getting the info from field of PatientName for updating the appointments AppStatus
        Name = self.NameLE.text()
        db = sqlite3.connect("Hospital.db")
        # Update Appointment if it matches with the Name
        db.execute("update PatientAppointment set AppStatus='Approved' where FullName = " + "'" + Name + "'")
        db.commit()  # save
        # Selecting everything from appointments and view it in tableWidgets
        result = db.execute("select * from PatientAppointment")
        self.tableWidget.setRowCount(0)
        # Using two for loops to insert the data into tableWidgets
        for RowNum, RowDATA in enumerate(result):
            self.tableWidget.insertRow(RowNum)  # adding row number
            for ColumnNum, ColumnData in enumerate(RowDATA):
                self.tableWidget.setItem(RowNum, ColumnNum,QtWidgets.QTableWidgetItem(str(ColumnData)))  # col Data is Appointment
        db.close()
        self.NameLE.clear()  # Clearing Patient Name when it is done

    # Function for Denying Appoinments
    def DenyApp(self):
        # Getting the Name from the user
        Name = self.NameLE.text()
        db = sqlite3.connect("Hospital.db")
        # Updating the AppStatus to Denied if it matches with the name
        db.execute("update PatientAppointment set AppStatus='Denied' where FullName = " + "'" + Name + "'")
        db.commit()
        # Selecting everything after updating Appointment to show it in tableWidget
        result = db.execute("select * from PatientAppointment")
        self.tableWidget.setRowCount(0)
        # Using two for loops to insert the data into Rows and columns
        for RowNum, RowDATA in enumerate(result):
            self.tableWidget.insertRow(RowNum)  # Inserting Row Get_Number
            for ColumnNum, ColumnData in enumerate(RowDATA):
                self.tableWidget.setItem(RowNum, ColumnNum,QtWidgets.QTableWidgetItem(str(ColumnData)))
        db.close()
        self.NameLE.clear()  # Clearing Patient Name after it is donw

    def ShowAppointments(self):
        db=sqlite3.connect("Hospital.db")
        result= db.execute("Select * from PatientAppointment")

        # Set the row count to be zero in order to show all the info that matches with email
        self.tableWidget.setRowCount(0)
        for RowNum, RowData in enumerate(result):
            self.tableWidget.insertRow(RowNum)
            for columnNum, columnData in enumerate(RowData):
                self.tableWidget.setItem(RowNum, columnNum, QtWidgets.QTableWidgetItem(str(columnData)))

        db.close()
        print('show')





    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 405)
        MainWindow.setStyleSheet("background-color: rgb(192, 192, 192);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LogoutBTN = QtWidgets.QPushButton(self.centralwidget)
        self.LogoutBTN.setGeometry(QtCore.QRect(0, 0, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.LogoutBTN.setFont(font)
        self.LogoutBTN.setStyleSheet("background-color: rgb(89, 128, 255);")
        self.LogoutBTN.setObjectName("LogoutBTN")
        self.LogoutBTN.clicked.connect(self.close)
        
        self.ApproveBTN = QtWidgets.QPushButton(self.centralwidget)
        self.ApproveBTN.setGeometry(QtCore.QRect(360, 350, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.ApproveBTN.setFont(font)
        self.ApproveBTN.setStyleSheet("background-color: rgb(89, 128, 255);")
        self.ApproveBTN.setObjectName("ApproveBTN")
        ### activate approve button
        self.ApproveBTN.clicked.connect(self.ApproveApp)

        self.DenyBTN = QtWidgets.QPushButton(self.centralwidget)
        self.DenyBTN.setGeometry(QtCore.QRect(490, 350, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.DenyBTN.setFont(font)
        self.DenyBTN.setStyleSheet("background-color: rgb(89, 128, 255);")
        self.DenyBTN.setObjectName("DenyBTN")
        #### activate deniy button
        self.DenyBTN.clicked.connect(self.DenyApp)


        self.ShowAppBTN = QtWidgets.QPushButton(self.centralwidget)
        self.ShowAppBTN.setGeometry(QtCore.QRect(650, 310, 151, 31))
        ### to activate show appointment
        self.ShowAppBTN.clicked.connect(self.ShowAppointments)


        font = QtGui.QFont()
        font.setFamily("Courier")
        self.ShowAppBTN.setFont(font)
        self.ShowAppBTN.setStyleSheet("background-color: rgb(89, 128, 255);")
        self.ShowAppBTN.setObjectName("ShowAppBTN")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 150, 791, 161))
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("background-color: rgb(238, 240, 244);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 340, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.NameLE = QtWidgets.QLineEdit(self.centralwidget)
        self.NameLE.setGeometry(QtCore.QRect(130, 340, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.NameLE.setFont(font)
        self.NameLE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.NameLE.setObjectName("NameLE")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(340, 50, 131, 51))
        self.label_8.setStyleSheet("image: url(:/background/images.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LogoutBTN.setText(_translate("MainWindow", "Logout "))
        self.ApproveBTN.setText(_translate("MainWindow", "Approve"))
        self.DenyBTN.setText(_translate("MainWindow", "Deny"))
        self.ShowAppBTN.setText(_translate("MainWindow", "Show Appointments"))
        self.label_2.setText(_translate("MainWindow", "Appointments"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "App Status"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Patient Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Patient Age"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Patient Phone"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Patient Gender"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Medical Condition"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Scheduled Day of Appointment"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Time of Appointment"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Email"))
        self.label_3.setText(_translate("MainWindow", "Patients Name"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Reception()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
